apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: floresguamanmoralesnarvaez
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: billing-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: billing-service-config
            - secretRef:
                name: billing-service-secrets
          readinessProbe:
            tcpSocket:
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 3002
            initialDelaySeconds: 25
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "256Mi"
              cpu: "150m"
