apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-service-config
  namespace: FloresGuamanMoralesNarvaez
data:
  PORT: "8001"
  DATABASE_URL: "postgresql://postgres:admin@ticket-db:5432/tickets"
  USUARIOS_API_URL: "http://auth-service:8000"
  VEHICULOS_API_URL: "http://auth-service:8000"
  ZONAS_API_URL: "http://parking-service:8080"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
