apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
  namespace: floresguamanmoralesnarvaez
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: ticket-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: ticket-service-config
            - secretRef:
                name: ticket-service-secrets
          readinessProbe:
            httpGet:
              path: /tickets/
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /tickets/
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
