apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: floresguamanmoralesnarvaez
data:
  PORT: "3003"
  DATABASE_URL: "postgresql://notification_user:notification_pass@notification-db:5432/notification_db"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
