apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-pvc
  namespace: floresguamanmoralesnarvaez
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parking-db-pvc
  namespace: floresguamanmoralesnarvaez
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ticket-db-pvc
  namespace: floresguamanmoralesnarvaez
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: billing-db-pvc
  namespace: floresguamanmoralesnarvaez
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-db-pvc
  namespace: floresguamanmoralesnarvaez
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
