apiVersion: v1
kind: Secret
metadata:
  name: databases-secrets
  namespace: floresguamanmoralesnarvaez
type: Opaque
stringData:
  AUTH_DB_PASS: "admin"
  PARKING_DB_PASS: "zonas_pass"
  TICKET_DB_PASS: "admin"
  BILLING_DB_PASS: "billing_pass"
  NOTIFICATION_DB_PASS: "notification_pass"
