apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-service
  namespace: floresguamanmoralesnarvaez
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking-service
  template:
    metadata:
      labels:
        app: parking-service
    spec:
      containers:
        - name: parking-service
          image: parking-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: parking-service-config
            - secretRef:
                name: parking-service-secrets
          readinessProbe:
            httpGet:
              path: /api/v1/espacios/listar
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/espacios/listar
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "30m"
            limits:
              memory: "300Mi"
              cpu: "200m"
