apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: narvaezsolismorales
data:
  KONG_DATABASE: "off"
  KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
  KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
  KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
