apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-service-config
  namespace: floresguamanmoralesnarvaez
data:
  PORT: "3002"
  DB_HOST: "billing-db"
  DB_PORT: "5432"
  DB_USUARIO: "billing_user"
  DB_NOMBRE: "billing_db"
  RABBITMQ_HOST: "rabbitmq"
