spring:
  application:
    name: zonas
  mvc:
    problemdetails:
      enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT_NUM:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/zonas_db}
    username: ${DB_USERNAME:zonas_user}
    password: ${DB_PASSWORD:zonas_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  swagger-ui:
    path: /zonas/docs
  api-docs:
    path: /zonas/openapi.json

server:
  port: ${PORT:8080}
  error:
    include-message: always

app:
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:audit_exchange}
    routing-key: ${RABBITMQ_ROUTING_KEY:audit.#}
