server {
    listen 8080;
    server_name localhost;

    # Ocultar la versión de Nginx en cabeceras y páginas de error
    server_tokens off;

    # Limitar el tamaño máximo del cuerpo de peticiones HTTP a 1MB
    client_max_body_size 1M;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
