apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: floresguamanmoralesnarvaez
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-service-secrets
          readinessProbe:
            httpGet:
              path: /usuarios/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /usuarios/health
              port: 8000
            initialDelaySeconds: 25
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "256Mi"
              cpu: "150m"
