apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: floresguamanmoralesnarvaez
type: Opaque
stringData:
  JWT_SECRET: "secreto-super-seguro-jwt-key"
  RABBITMQ_PASSWORD: "guest"
