apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
  namespace: floresguamanmoralesnarvaez
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: ticket-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: ticket-service-config
            - secretRef:
                name: ticket-service-secrets
          readinessProbe:
            httpGet:
              path: /tickets/
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /tickets/
              port: 8001
            initialDelaySeconds: 25
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "256Mi"
              cpu: "150m"
