apiVersion: v1
kind: Secret
metadata:
  name: ticket-service-secrets
  namespace: FloresGuamanMoralesNarvaez
type: Opaque
stringData:
  JWT_SECRET: "secreto-super-seguro-jwt-key"
  RABBITMQ_PASSWORD: "guest"
