apiVersion: v1
kind: Service
metadata:
  name: asignacion-service
  namespace: floresguamanmoralesnarvaez
spec:
  selector:
    app: asignacion-service
  ports:
    - port: 3001
      targetPort: 3001
