apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: floresguamanmoralesnarvaez

resources:
  - infrastructure/00-namespace.yml
  - infrastructure/databases/deployment
  - infrastructure/rabbitmq/deployment
  - backend/auth-service/deployment
  - backend/parking-service/deployment
  - backend/ticket-service/deployment
  - backend/billing-service/deployment
  - backend/notification-service/deployment
  - backend/vehiculos/deployment
  - backend/asignacion-trazabilidad/deployment
  - gateway/deployment
  - frontend/deployment
